-- MySQL Script generated by MySQL Workbench
-- Fri May 28 20:31:59 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema гардероб
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema гардероб
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `гардероб` DEFAULT CHARACTER SET utf8 ;
USE `гардероб` ;

-- -----------------------------------------------------
-- Table `гардероб`.`склад`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `гардероб`.`склад` (
  `id_Склад` INT NOT NULL,
  `Списание` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_Склад`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `гардероб`.`документ_гп`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `гардероб`.`документ_гп` (
  `id_Документа` INT NOT NULL,
  `Списание` VARCHAR(45) NULL DEFAULT NULL,
  `Дата_создания` DATETIME NULL DEFAULT NULL,
  `Статус` VARCHAR(45) NULL DEFAULT NULL,
  `id_Склад` INT NOT NULL,
  PRIMARY KEY (`id_Документа`),
  INDEX `fk_Документ_ГП_Склад1_idx` (`id_Склад` ASC) VISIBLE,
  CONSTRAINT `fk_Документ_ГП_Склад1`
    FOREIGN KEY (`id_Склад`)
    REFERENCES `гардероб`.`склад` (`id_Склад`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `гардероб`.`мк`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `гардероб`.`мк` (
  `id_МК` INT NOT NULL,
  `Дата_изменения` DATETIME(6) NULL DEFAULT NULL,
  `Статус` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_МК`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `гардероб`.`спецификация`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `гардероб`.`спецификация` (
  `id_Спецификация` INT NOT NULL,
  `Статус` VARCHAR(45) NULL DEFAULT NULL,
  `Дата_изменения` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id_Спецификация`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `гардероб`.`нп`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `гардероб`.`нп` (
  `id_НП` INT NOT NULL,
  `Метод_списания` VARCHAR(45) NULL DEFAULT NULL,
  `Наименование` VARCHAR(45) NULL DEFAULT NULL,
  `Ед_измерения` DECIMAL(5,2) NULL DEFAULT NULL,
  `Метод_возобновления` VARCHAR(45) NULL DEFAULT NULL,
  `Точка_доказа` INT NULL DEFAULT NULL,
  `Количество_для_заказа` INT NULL DEFAULT NULL,
  `Период_ожидания` TIME NULL DEFAULT NULL,
  `Спецификация_id_Спецификация` INT NOT NULL,
  `МК_id_МК` INT NOT NULL,
  PRIMARY KEY (`id_НП`),
  INDEX `fk_НП_Спецификация1_idx` (`Спецификация_id_Спецификация` ASC) VISIBLE,
  INDEX `fk_НП_МК1_idx` (`МК_id_МК` ASC) VISIBLE,
  CONSTRAINT `fk_НП_МК1`
    FOREIGN KEY (`МК_id_МК`)
    REFERENCES `гардероб`.`мк` (`id_МК`),
  CONSTRAINT `fk_НП_Спецификация1`
    FOREIGN KEY (`Спецификация_id_Спецификация`)
    REFERENCES `гардероб`.`спецификация` (`id_Спецификация`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `гардероб`.`пз`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `гардероб`.`пз` (
  `id_ПЗ` INT NOT NULL,
  `Списание` VARCHAR(45) NULL DEFAULT NULL,
  `Количество` INT NULL DEFAULT NULL,
  `Дата_начала` DATETIME(6) NULL DEFAULT NULL,
  `Дата_завершения` DATETIME(6) NULL DEFAULT NULL,
  `Статус` VARCHAR(45) NULL DEFAULT NULL,
  `id_НП` INT NOT NULL,
  PRIMARY KEY (`id_ПЗ`),
  INDEX `fk_ПЗ_НП1_idx` (`id_НП` ASC) VISIBLE,
  CONSTRAINT `fk_ПЗ_НП1`
    FOREIGN KEY (`id_НП`)
    REFERENCES `гардероб`.`нп` (`id_НП`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `гардероб`.`документ_поступления`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `гардероб`.`документ_поступления` (
  `id_Документа` INT NOT NULL,
  `Списание` VARCHAR(45) NULL DEFAULT NULL,
  `Дата_создания` DATETIME NULL DEFAULT NULL,
  `Статус` VARCHAR(45) NULL DEFAULT NULL,
  `id_Склад` INT NOT NULL,
  `пз_id_ПЗ` INT NOT NULL,
  PRIMARY KEY (`id_Документа`),
  INDEX `fk_Документ_Поступления_Склад_idx` (`id_Склад` ASC) VISIBLE,
  INDEX `fk_документ_поступления_пз1_idx` (`пз_id_ПЗ` ASC) VISIBLE,
  CONSTRAINT `fk_Документ_Поступления_Склад`
    FOREIGN KEY (`id_Склад`)
    REFERENCES `гардероб`.`склад` (`id_Склад`),
  CONSTRAINT `fk_документ_поступления_пз1`
    FOREIGN KEY (`пз_id_ПЗ`)
    REFERENCES `гардероб`.`пз` (`id_ПЗ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `гардероб`.`документ_реализации`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `гардероб`.`документ_реализации` (
  `id_Документа` INT NOT NULL,
  `Списание` VARCHAR(45) NULL DEFAULT NULL,
  `Дата_создания` DATETIME NULL DEFAULT NULL,
  `Статус` VARCHAR(45) NULL DEFAULT NULL,
  `id_Склад` INT NOT NULL,
  `пз_id_ПЗ` INT NOT NULL,
  PRIMARY KEY (`id_Документа`),
  INDEX `fk_Документ_Реализации_Склад1_idx` (`id_Склад` ASC) VISIBLE,
  INDEX `fk_документ_реализации_пз1_idx` (`пз_id_ПЗ` ASC) VISIBLE,
  CONSTRAINT `fk_Документ_Реализации_Склад1`
    FOREIGN KEY (`id_Склад`)
    REFERENCES `гардероб`.`склад` (`id_Склад`),
  CONSTRAINT `fk_документ_реализации_пз1`
    FOREIGN KEY (`пз_id_ПЗ`)
    REFERENCES `гардероб`.`пз` (`id_ПЗ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `гардероб`.`документ_списания`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `гардероб`.`документ_списания` (
  `id_Документа` INT NOT NULL,
  `Списание` VARCHAR(45) NULL DEFAULT NULL,
  `Дата_создания` DATETIME NULL DEFAULT NULL,
  `Статус` VARCHAR(45) NULL DEFAULT NULL,
  `id_Склад` INT NOT NULL,
  `пз_id_ПЗ` INT NOT NULL,
  PRIMARY KEY (`id_Документа`),
  INDEX `fk_Документ_Списания_Склад1_idx` (`id_Склад` ASC) VISIBLE,
  INDEX `fk_документ_списания_пз1_idx` (`пз_id_ПЗ` ASC) VISIBLE,
  CONSTRAINT `fk_Документ_Списания_Склад1`
    FOREIGN KEY (`id_Склад`)
    REFERENCES `гардероб`.`склад` (`id_Склад`),
  CONSTRAINT `fk_документ_списания_пз1`
    FOREIGN KEY (`пз_id_ПЗ`)
    REFERENCES `гардероб`.`пз` (`id_ПЗ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `гардероб`.`журнал_потребления`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `гардероб`.`журнал_потребления` (
  `Потребление` INT NULL DEFAULT NULL,
  `Выход` INT NULL DEFAULT NULL,
  `id_Документа` INT NOT NULL,
  `id_ПЗ` INT NOT NULL,
  `id_НП` INT NOT NULL,
  PRIMARY KEY (`id_ПЗ`, `id_НП`),
  INDEX `fk_Товарные_Операции_ПЗ1_idx` (`id_ПЗ` ASC) VISIBLE,
  INDEX `fk_Товарные_Операции_НП1_idx` (`id_НП` ASC) VISIBLE,
  CONSTRAINT `fk_Товарные_Операции_Документ_ГП1`
    FOREIGN KEY (`id_Документа`)
    REFERENCES `гардероб`.`документ_гп` (`id_Документа`),
  CONSTRAINT `fk_Товарные_Операции_НП1`
    FOREIGN KEY (`id_НП`)
    REFERENCES `гардероб`.`нп` (`id_НП`),
  CONSTRAINT `fk_Товарные_Операции_ПЗ1`
    FOREIGN KEY (`id_ПЗ`)
    REFERENCES `гардероб`.`пз` (`id_ПЗ`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `гардероб`.`запас`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `гардероб`.`запас` (
  `Количество` INT NULL DEFAULT NULL,
  `id_Склад` INT NOT NULL,
  `id_НП` INT NOT NULL,
  PRIMARY KEY (`id_Склад`, `id_НП`),
  INDEX `fk_Запас_НП1_idx` (`id_НП` ASC) VISIBLE,
  CONSTRAINT `fk_Запас_НП1`
    FOREIGN KEY (`id_НП`)
    REFERENCES `гардероб`.`нп` (`id_НП`),
  CONSTRAINT `fk_Запас_Склад1`
    FOREIGN KEY (`id_Склад`)
    REFERENCES `гардероб`.`склад` (`id_Склад`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `гардероб`.`компонент`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `гардероб`.`компонент` (
  `Позиция` INT NOT NULL,
  `Количество` INT NULL DEFAULT NULL,
  `Ед_измерения` DECIMAL(5,2) NULL DEFAULT NULL,
  `id_НП` INT NOT NULL,
  `id_Спецификация` INT NOT NULL,
  PRIMARY KEY (`Позиция`, `id_Спецификация`),
  INDEX `fk_Компонент_НП1_idx` (`id_НП` ASC) VISIBLE,
  INDEX `fk_Компонент_Спецификация1_idx` (`id_Спецификация` ASC) VISIBLE,
  CONSTRAINT `fk_Компонент_НП1`
    FOREIGN KEY (`id_НП`)
    REFERENCES `гардероб`.`нп` (`id_НП`),
  CONSTRAINT `fk_Компонент_Спецификация1`
    FOREIGN KEY (`id_Спецификация`)
    REFERENCES `гардероб`.`спецификация` (`id_Спецификация`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `гардероб`.`рц`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `гардероб`.`рц` (
  `id_РЦ` INT NOT NULL,
  `Ежедневная_мощность` TIME NULL DEFAULT NULL,
  `Списание` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_РЦ`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `гардероб`.`операция`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `гардероб`.`операция` (
  `id_Операция` INT NOT NULL,
  `Время_обработки` TIME NULL DEFAULT NULL,
  `Время_перехода` TIME NULL DEFAULT NULL,
  `Время_наладки` TIME NULL DEFAULT NULL,
  `Следующая_операция` INT NOT NULL,
  `id_МК` INT NOT NULL,
  `РЦ_id_РЦ` INT NOT NULL,
  PRIMARY KEY (`id_Операция`, `id_МК`),
  INDEX `fk_Операция_МК1_idx` (`id_МК` ASC) VISIBLE,
  INDEX `fk_Операция_РЦ1_idx` (`РЦ_id_РЦ` ASC) VISIBLE,
  CONSTRAINT `fk_Операция_МК1`
    FOREIGN KEY (`id_МК`)
    REFERENCES `гардероб`.`мк` (`id_МК`),
  CONSTRAINT `fk_Операция_РЦ1`
    FOREIGN KEY (`РЦ_id_РЦ`)
    REFERENCES `гардероб`.`рц` (`id_РЦ`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `гардероб`.`состав_поступления`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `гардероб`.`состав_поступления` (
  `Количество` INT NULL DEFAULT NULL,
  `id_Документа` INT NOT NULL,
  `id_НП` INT NOT NULL,
  `Номер_Документа` INT NOT NULL,
  PRIMARY KEY (`id_Документа`),
  INDEX `fk_Состав_поступления_НП1_idx` (`id_НП` ASC) VISIBLE,
  CONSTRAINT `fk_Состав_поступления_Документ_По1`
    FOREIGN KEY (`id_Документа`)
    REFERENCES `гардероб`.`документ_поступления` (`id_Документа`),
  CONSTRAINT `fk_Состав_поступления_НП1`
    FOREIGN KEY (`id_НП`)
    REFERENCES `гардероб`.`нп` (`id_НП`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `гардероб`.`состав_реализации`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `гардероб`.`состав_реализации` (
  `Количество` INT NULL DEFAULT NULL,
  `id_Документа` INT NOT NULL,
  `НП_id_НП` INT NOT NULL,
  `Номер_Документа` INT NOT NULL,
  PRIMARY KEY (`id_Документа`),
  INDEX `fk_Состав_Реализации_НП1_idx` (`НП_id_НП` ASC) VISIBLE,
  CONSTRAINT `fk_Состав_Реализации_Документ_Реа1`
    FOREIGN KEY (`id_Документа`)
    REFERENCES `гардероб`.`документ_реализации` (`id_Документа`),
  CONSTRAINT `fk_Состав_Реализации_НП1`
    FOREIGN KEY (`НП_id_НП`)
    REFERENCES `гардероб`.`нп` (`id_НП`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `гардероб`.`состав_списания`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `гардероб`.`состав_списания` (
  `Количество` INT NULL DEFAULT NULL,
  `id_Документа` INT NOT NULL,
  `id_НП` INT NOT NULL,
  `Номер_Документа` INT NOT NULL,
  PRIMARY KEY (`id_Документа`),
  INDEX `fk_Состав_списания_НП1_idx` (`id_НП` ASC) VISIBLE,
  CONSTRAINT `fk_Состав_списания_Документ_Списа1`
    FOREIGN KEY (`id_Документа`)
    REFERENCES `гардероб`.`документ_списания` (`id_Документа`),
  CONSTRAINT `fk_Состав_списания_НП1`
    FOREIGN KEY (`id_НП`)
    REFERENCES `гардероб`.`нп` (`id_НП`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `гардероб`.`учтенные_операции_мощности`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `гардероб`.`учтенные_операции_мощности` (
  `Затраченное_время` TIME NULL DEFAULT NULL,
  `id_ПЗ` INT NOT NULL,
  `Операция` INT NOT NULL,
  `рц_id_РЦ` INT NOT NULL,
  PRIMARY KEY (`id_ПЗ`, `Операция`),
  INDEX `fk_Учтенные_операции_мощности_Операция` (`Операция` ASC) VISIBLE,
  INDEX `fk_учтенные_операции_мощности_рц1_idx` (`рц_id_РЦ` ASC) VISIBLE,
  CONSTRAINT `fk_Учтенные_операции_мощности_Операция`
    FOREIGN KEY (`Операция`)
    REFERENCES `гардероб`.`операция` (`id_Операция`),
  CONSTRAINT `fk_Учтенные_операции_мощности_ПЗ1`
    FOREIGN KEY (`id_ПЗ`)
    REFERENCES `гардероб`.`пз` (`id_ПЗ`),
  CONSTRAINT `fk_учтенные_операции_мощности_рц1`
    FOREIGN KEY (`рц_id_РЦ`)
    REFERENCES `гардероб`.`рц` (`id_РЦ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
